// Code generated by go-vk from vk.xml at 2023-08-03 23:07:41.027829108 +0200 CEST m=+2.730772282. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
