// Code generated by go-vk from vk.xml at 2023-08-03 23:04:04.733177295 +0200 CEST m=+2.711845104. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
