// Code generated by go-vk from vk.xml at 2023-08-03 23:04:04.738814507 +0200 CEST m=+2.717482316. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
