// Code generated by go-vk from vk.xml at 2023-08-03 23:04:04.858949148 +0200 CEST m=+2.837616957. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
