//go:build darwin

// Code generated by go-vk from vk.xml at 2023-08-03 23:07:40.893037558 +0200 CEST m=+2.595980730. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_OBJECTS_EXTENSION_NAME = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION   = 1
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
