//go:build darwin

// Code generated by go-vk from vk.xml at 2023-08-03 23:07:41.15200387 +0200 CEST m=+2.854947032. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
