// Code generated by go-vk from vk.xml at 2023-08-03 23:04:04.481291015 +0200 CEST m=+2.459958836. DO NOT EDIT.

package vk

// Extension names and versions
const (
	AMD_GPU_SHADER_HALF_FLOAT_SPEC_VERSION                   = 2
	AMD_RASTERIZATION_ORDER_EXTENSION_NAME                   = "VK_AMD_rasterization_order"
	AMD_SHADER_BALLOT_SPEC_VERSION                           = 1
	AMD_SHADER_FRAGMENT_MASK_EXTENSION_NAME                  = "VK_AMD_shader_fragment_mask"
	AMD_SHADER_TRINARY_MINMAX_EXTENSION_NAME                 = "VK_AMD_shader_trinary_minmax"
	ARM_SHADER_CORE_BUILTINS_SPEC_VERSION                    = 2
	EXT_CUSTOM_BORDER_COLOR_SPEC_VERSION                     = 12
	EXT_FRAGMENT_SHADER_INTERLOCK_SPEC_VERSION               = 1
	EXT_HEADLESS_SURFACE_SPEC_VERSION                        = 1
	EXT_HOST_QUERY_RESET_EXTENSION_NAME                      = "VK_EXT_host_query_reset"
	EXT_IMAGE_COMPRESSION_CONTROL_SPEC_VERSION               = 1
	EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME = "VK_EXT_multisampled_render_to_single_sampled"
	EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_SPEC_VERSION   = 1
	EXT_MUTABLE_DESCRIPTOR_TYPE_SPEC_VERSION                 = 1
	EXT_NON_SEAMLESS_CUBE_MAP_EXTENSION_NAME                 = "VK_EXT_non_seamless_cube_map"
	EXT_PCI_BUS_INFO_SPEC_VERSION                            = 2
	EXT_PIPELINE_CREATION_CACHE_CONTROL_EXTENSION_NAME       = "VK_EXT_pipeline_creation_cache_control"
	EXT_ROBUSTNESS_2_EXTENSION_NAME                          = "VK_EXT_robustness2"
	EXT_SHADER_ATOMIC_FLOAT_SPEC_VERSION                     = 1
	EXT_SHADER_OBJECT_SPEC_VERSION                           = 1
	EXT_SHADER_STENCIL_EXPORT_SPEC_VERSION                   = 1
	EXT_SHADER_VIEWPORT_INDEX_LAYER_EXTENSION_NAME           = "VK_EXT_shader_viewport_index_layer"
	EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME                    = "VK_EXT_transform_feedback"
	KHR_8BIT_STORAGE_EXTENSION_NAME                          = "VK_KHR_8bit_storage"
	KHR_DEVICE_GROUP_CREATION_EXTENSION_NAME                 = "VK_KHR_device_group_creation"
	KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME                     = "VK_KHR_display_swapchain"
	KHR_EXTERNAL_MEMORY_CAPABILITIES_SPEC_VERSION            = 1
	KHR_EXTERNAL_MEMORY_EXTENSION_NAME                       = "VK_KHR_external_memory"
	KHR_RAY_TRACING_PIPELINE_SPEC_VERSION                    = 1
	KHR_SHADER_CLOCK_EXTENSION_NAME                          = "VK_KHR_shader_clock"
	KHR_SHARED_PRESENTABLE_IMAGE_SPEC_VERSION                = 1
	KHR_SPIRV_1_4_EXTENSION_NAME                             = "VK_KHR_spirv_1_4"
	KHR_TIMELINE_SEMAPHORE_EXTENSION_NAME                    = "VK_KHR_timeline_semaphore"
	KHR_VIDEO_DECODE_QUEUE_SPEC_VERSION                      = 7
	NV_COPY_MEMORY_INDIRECT_SPEC_VERSION                     = 1
	NV_RAY_TRACING_MOTION_BLUR_SPEC_VERSION                  = 1
	NV_SAMPLE_MASK_OVERRIDE_COVERAGE_SPEC_VERSION            = 1
	QCOM_RENDER_PASS_STORE_OPS_SPEC_VERSION                  = 2
)
